  workflow_dispatch:
    inputs:
      publish-to-dockerhub:
        description: 'Publish to Dockerhub?'
        type: boolean
        required: true
        default: true
      publish-to-ghcr:
        description: 'Publish to GitHub container registry?'
        type: boolean
        required: true
        default: true

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.step-version-bump.outputs.OLD_VERSION }}
    steps:
      - uses: actions/checkout@master
      - name: Version bump
        id: step-version-bump
        uses: papermerge/banger@master
        with:
          files_list: "package.json,app/version.js"

  build-and-publish-to-dockerhub:
    name: Dockerhub build/push
    needs: extract-version
    if: ${{ github.event.inputs.publish-to-dockerhub == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: papermerge/papermerge.js:${{needs.extract-version.outputs.old-version}}
          file: docker/Dockerfile

  build-and-publish-to-ghcr:
    name: ghcr.io build/push
    if: ${{ github.event.inputs.publish-to-ghcr == 'true' }}
    needs: extract-version
    runs-on: ubuntu-latest
    env:
      papermerge_js_image: ghcr.io/papermerge/papermerge.js
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.papermerge_js_image }}:${{needs.extract-version.outputs.old-version}}, ${{ env.papermerge_js_image }}:latest
          file: docker/Dockerfile
